name: Build and Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  next-build:
    name: Build Next.js Project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "24"

      - name: Install dependencies
        run: npm install

      - name: Build next project
        run: npm run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: next-build
          path: ./out

  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    needs: next-build

    # Grant GITHUB_TOKEN the permissions required to make a Pages deployment
    permissions:
      pages: write # to deploy to Pages
      id-token: write # to verify the deployment originates from an appropriate source

    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: next-build

      - name: Publish to GitHub Pages 🚀
        uses: actions/deploy-pages@v4
